// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * W​i​n​t​r​y
	 */
	wintry: string
	settings: {
		sections: {
			/**
			 * P​l​u​g​i​n​s
			 */
			plugins: string
			/**
			 * T​h​e​m​e​s
			 */
			themes: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Wintry
	 */
	wintry: () => LocalizedString
	settings: {
		sections: {
			/**
			 * Plugins
			 */
			plugins: () => LocalizedString
			/**
			 * Themes
			 */
			themes: () => LocalizedString
		}
	}
}

export type Formatters = {}
